// <auto-generated />
using System;
using ChatbotIaJuridico.Infra.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatbotIaJuridico.Infra.Migrations
{
    [DbContext(typeof(ChatbotIaJuridicoContext))]
    [Migration("20250220130819_ScriptAtualizado_20_02_2025")]
    partial class ScriptAtualizado_20_02_2025
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Advogado", b =>
                {
                    b.Property<int>("AdvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("adv_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdvId"));

                    b.Property<int>("AdvCpf")
                        .HasColumnType("int")
                        .HasColumnName("adv_cpf");

                    b.Property<string>("AdvNome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("adv_nome");

                    b.Property<string>("AdvSenha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("adv_senha");

                    b.Property<string>("AdvWaid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("adv_waid");

                    b.HasKey("AdvId")
                        .HasName("PK__advogado__D4518D542DBC5CDA");

                    b.ToTable("advogado");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Chat", b =>
                {
                    b.Property<int>("ChaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cha_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChaId"));

                    b.Property<int>("AdvId")
                        .HasColumnType("int")
                        .HasColumnName("adv_id");

                    b.Property<int>("ChaEstado")
                        .HasColumnType("int")
                        .HasColumnName("cha_estado");

                    b.HasKey("ChaId")
                        .HasName("PK__chat__5AF8FDEA4C906010");

                    b.HasIndex("AdvId");

                    b.ToTable("chat");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Cliente", b =>
                {
                    b.Property<int>("CliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cli_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CliId"));

                    b.Property<int>("CliCpf")
                        .HasColumnType("int")
                        .HasColumnName("cli_cpf");

                    b.Property<string>("CliNome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cli_nome");

                    b.HasKey("CliId")
                        .HasName("PK__cliente__FFEFE14F9FCA56EF");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.ConfiguracaoGeral", b =>
                {
                    b.Property<int>("ConfgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("confg_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfgId"));

                    b.Property<string>("ConfDescricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("conf_descricao");

                    b.Property<bool?>("ConfgAtiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("confg_ativa");

                    b.Property<string>("ConfgValor")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("confg_valor");

                    b.HasKey("ConfgId")
                        .HasName("PK__configur__96AC3BF468906048");

                    b.ToTable("configuracaoGeral");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Insumo", b =>
                {
                    b.Property<int>("InsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ins_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsId"));

                    b.Property<int>("AdvId")
                        .HasColumnType("int")
                        .HasColumnName("adv_id");

                    b.Property<int>("ChaId")
                        .HasColumnType("int")
                        .HasColumnName("cha_id");

                    b.Property<string>("InsCaminho")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ins_caminho");

                    b.Property<DateTime?>("InsData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ins_data")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("InsDescricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ins_descricao");

                    b.Property<int>("InsTipo")
                        .HasColumnType("int")
                        .HasColumnName("ins_tipo");

                    b.Property<int>("PProcId")
                        .HasColumnType("int")
                        .HasColumnName("pProc_id");

                    b.HasKey("InsId")
                        .HasName("PK__insumo__9CB72D205B7BA2C0");

                    b.HasIndex("AdvId");

                    b.HasIndex("ChaId");

                    b.HasIndex("PProcId");

                    b.ToTable("insumo");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Menu", b =>
                {
                    b.Property<int>("MenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("men_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenId"));

                    b.Property<string>("MenBody")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("men_body");

                    b.Property<string>("MenFooter")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("men_footer");

                    b.Property<string>("MenHeader")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("men_header");

                    b.Property<int>("MenTipo")
                        .HasColumnType("int")
                        .HasColumnName("men_tipo");

                    b.Property<string>("MenTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("men_title");

                    b.HasKey("MenId")
                        .HasName("PK__menus__387DDE001B9A5F69");

                    b.ToTable("menus");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Option", b =>
                {
                    b.Property<int>("OptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("opt_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptId"));

                    b.Property<int>("MenId")
                        .HasColumnType("int")
                        .HasColumnName("men_id");

                    b.Property<DateTime?>("OptData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("opt_data")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("OptDescricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("opt_descricao");

                    b.Property<bool?>("OptFinalizar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("opt_finalizar");

                    b.Property<string>("OptResposta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("opt_resposta");

                    b.Property<int>("OptTipo")
                        .HasColumnType("int")
                        .HasColumnName("opt_tipo");

                    b.Property<string>("OptTitle")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("opt_title");

                    b.HasKey("OptId")
                        .HasName("PK__options__84DB9F9B3BF3AA01");

                    b.HasIndex("MenId");

                    b.ToTable("options");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Peticao", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pet_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetId"));

                    b.Property<int>("AdvId")
                        .HasColumnType("int")
                        .HasColumnName("adv_id");

                    b.Property<string>("PProcCaminho")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("pProc_caminho");

                    b.Property<DateTime?>("PProcDataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("pProc_dataCriacao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PProcDescricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pProc_descricao");

                    b.Property<int>("PetTipo")
                        .HasColumnType("int")
                        .HasColumnName("pet_tipo");

                    b.HasKey("PetId")
                        .HasName("PK__peticao__390CC5FE5CAD68A5");

                    b.HasIndex("AdvId");

                    b.ToTable("peticao");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.PreProcesso", b =>
                {
                    b.Property<int>("PProcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pProc_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PProcId"));

                    b.Property<int>("AdvId")
                        .HasColumnType("int")
                        .HasColumnName("adv_id");

                    b.Property<int>("CliId")
                        .HasColumnType("int")
                        .HasColumnName("cli_id");

                    b.Property<DateTime?>("PProcDataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("pProc_dataCriacao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PProcDescricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pProc_descricao");

                    b.Property<int?>("PProcEstado")
                        .HasColumnType("int")
                        .HasColumnName("pProc_estado");

                    b.Property<string>("PProcNome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pProc_nome");

                    b.HasKey("PProcId")
                        .HasName("PK__preProce__51C4924FD8446F3A");

                    b.HasIndex("AdvId");

                    b.HasIndex("CliId");

                    b.ToTable("preProcesso");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Prompt", b =>
                {
                    b.Property<int>("PrompId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("promp_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrompId"));

                    b.Property<bool?>("PrompAtiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("promp_ativa");

                    b.Property<string>("PrompDescricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("promp_descricao");

                    b.Property<string>("PrompValor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("promp_valor");

                    b.HasKey("PrompId")
                        .HasName("PK__prompt__DC4E3490D2109AD1");

                    b.ToTable("prompt");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Chat", b =>
                {
                    b.HasOne("ChatbotIaJuridico.Infra.Advogado", "Adv")
                        .WithMany("Chats")
                        .HasForeignKey("AdvId")
                        .IsRequired()
                        .HasConstraintName("FK__chat__adv_id__440B1D61");

                    b.Navigation("Adv");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Insumo", b =>
                {
                    b.HasOne("ChatbotIaJuridico.Infra.Advogado", "Adv")
                        .WithMany("Insumos")
                        .HasForeignKey("AdvId")
                        .IsRequired()
                        .HasConstraintName("FK__insumo__adv_id__47DBAE45");

                    b.HasOne("ChatbotIaJuridico.Infra.Chat", "Cha")
                        .WithMany("Insumos")
                        .HasForeignKey("ChaId")
                        .IsRequired()
                        .HasConstraintName("FK__insumo__cha_id__49C3F6B7");

                    b.HasOne("ChatbotIaJuridico.Infra.PreProcesso", "PProc")
                        .WithMany("Insumos")
                        .HasForeignKey("PProcId")
                        .IsRequired()
                        .HasConstraintName("FK__insumo__pProc_id__48CFD27E");

                    b.Navigation("Adv");

                    b.Navigation("Cha");

                    b.Navigation("PProc");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Option", b =>
                {
                    b.HasOne("ChatbotIaJuridico.Infra.Menu", "Men")
                        .WithMany("Options")
                        .HasForeignKey("MenId")
                        .IsRequired()
                        .HasConstraintName("FK__options__men_id__5070F446");

                    b.Navigation("Men");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Peticao", b =>
                {
                    b.HasOne("ChatbotIaJuridico.Infra.Advogado", "Adv")
                        .WithMany("Peticaos")
                        .HasForeignKey("AdvId")
                        .IsRequired()
                        .HasConstraintName("FK__peticao__adv_id__412EB0B6");

                    b.Navigation("Adv");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.PreProcesso", b =>
                {
                    b.HasOne("ChatbotIaJuridico.Infra.Advogado", "Adv")
                        .WithMany("PreProcessos")
                        .HasForeignKey("AdvId")
                        .IsRequired()
                        .HasConstraintName("FK__preProces__adv_i__3C69FB99");

                    b.HasOne("ChatbotIaJuridico.Infra.Cliente", "Cli")
                        .WithMany("PreProcessos")
                        .HasForeignKey("CliId")
                        .IsRequired()
                        .HasConstraintName("FK__preProces__cli_i__3D5E1FD2");

                    b.Navigation("Adv");

                    b.Navigation("Cli");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Advogado", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Insumos");

                    b.Navigation("Peticaos");

                    b.Navigation("PreProcessos");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Chat", b =>
                {
                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Cliente", b =>
                {
                    b.Navigation("PreProcessos");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.Menu", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("ChatbotIaJuridico.Infra.PreProcesso", b =>
                {
                    b.Navigation("Insumos");
                });
#pragma warning restore 612, 618
        }
    }
}
