<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext7" Version="9.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChatbotIaJuridico.Domain\ChatbotIaJuridico.Domain.csproj" />
    <ProjectReference Include="..\ChatbotIaJuridico.Infra.Storage\ChatbotIaJuridico.Infra.Storage.csproj" />
  </ItemGroup>

</Project>
