namespace ChatbotIaJuridico.Domain.Models.Enum
{
    public enum EPeticaoTipo
    {
        AcaoDeclaratoria = 1,
        AcaoMonitoria = 2,
        AcaoOrdinaria = 3,
        AcaoPenal = 4,
        AcaoPopular = 5,
        AcaoRescisoria = 6,
        AcaoRevisao = 7,
        AcaoTrabalhista = 8,
        Agravo = 9,
        AgravoInstrumento = 10,
        AgravoInstrumentoRetido = 11,
        AgravoRegimental = 12,
        AgravoRetido = 13,
        Alvara = 14,
        AlvaraLevantamento = 15,
        AlvaraPagamento = 16,
        AlvaraPenhora = 17,
        AlvaraSaque = 18,
        AlvaraVista = 19,
        Apelacao = 20,
        ApelacaoCivel = 21,
        ApelacaoCriminal = 22,
        ApelacaoFamilia = 23,
        ApelacaoInfancia = 24,
        ApelacaoJuizado = 25,
        ApelacaoTribunal = 26,
        ApelacaoUnica = 27,
        ApelacaoUnicaCivel = 28,
        ApelacaoUnicaCriminal = 29,
        ApelacaoUnicaFamilia = 30,
        ApelacaoUnicaInfancia = 31,
        ApelacaoUnicaJuizado = 32,
        ApelacaoUnicaTribunal = 33,
        ApelacaoUnicaUnica = 34,
        ApelacaoUnicaUnicaCivel = 35,
        ApelacaoUnicaUnicaCriminal = 36,
        ApelacaoUnicaUnicaFamilia = 37,
        ApelacaoUnicaUnicaInfancia = 38,
        ApelacaoUnicaUnicaJuizado = 39,
        ApelacaoUnicaUnicaTribunal = 40,
        ApelacaoUnicaUnicaUnica = 41,
        ApelacaoUnicaUnicaUnicaCivel = 42,
        ApelacaoUnicaUnicaUnicaCriminal = 43,
        ApelacaoUnicaUnicaUnicaFamilia = 44,
    }
}
